import { Injectable } from '@angular/core';
import { Ingredient } from '../models/Ingredient.model';
import { Recipe } from '../models/Recipe.model';
import { User } from '../models/User.model';
import { Observable } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
@Injectable({
  providedIn: 'root'
})
export class HandleArraysService {

  public therecipes:Array<Recipe>=[
    //{id:1,name:'Beef',category:'turkey'}
    ];
  public meats:Array<Ingredient>=[
  {id:1,name:'Beef',category:'meats', weight:12},
  {id:2,name:'Chicken',category:'meats', weight:12},
  {id:3,name:'Turkey',category:'meats', weight:12},
  {id:4,name:'Pork',category:'meats', weight:12},
  {id:5,name:'Shrimp',category:'meats', weight:12},
  {id:6,name:'Salmon',category:'meats', weight:12},
  {id:7,name:'Tuna',category:'meats', weight:12},
  {id:8,name:'Tilapia',category:'meats', weight:12},
  {id:9,name:'Halibut',category:'meats', weight:12},
  {id:10,name:'Lamb',category:'meats', weight:12},
  {id:11,name:'Sardines',category:'meats', weight:12},
  {id:12,name:'Liver',category:'meats', weight:12},
  {id:13,name:'Ham',category:'meats', weight:12},
  {id:14,name:'Bacon',category:'meats', weight:12},
  {id:15,name:'Tripe',category:'meats', weight:12},
  {id:16,name:'Scallop',category:'meats', weight:12},
  {id:17,name:'Anchovies',category:'meats', weight:12},
  {id:18,name:'Lobster',category:'meats', weight:12},
  {id:19,name:'Steak',category:'meats', weight:12},
  {id:20,name:'Egg',category:'meats', weight:12},
  {id:21,name:'Tofu',category:'meats', weight:12},
  {id:22,name:'Tempeh',category:'meats', weight:12}




];
public veggies:Array<Ingredient>=[
  {id:23,name:'Broccoli',category:'veggies',weight:4},
  {id:24,name:'Squash',category:'veggies',weight:4},
  {id:25,name:'Spinach',category:'veggies',weight:4},
  {id:26,name:'Carrots',category:'veggies',weight:4},
  {id:27,name:'Onion',category:'veggies',weight:4},
  {id:28,name:'Cabbage',category:'veggies',weight:4},
  {id:29,name:'Zucchini',category:'veggies',weight:4},
  {id:30,name:'Eggplant',category:'veggies',weight:4},
  {id:31,name:'Corn',category:'veggies',weight:4},
  {id:32,name:'Lettuce',category:'veggies',weight:4},
  {id:33,name:'Chives',category:'veggies',weight:4},
  {id:34,name:'Asparagus',category:'veggies',weight:4},
  {id:35,name:'Garlic',category:'veggies',weight:4},
  {id:36,name:'Peas',category:'veggies',weight:4},
  {id:37,name:'Chickpea',category:'veggies',weight:4},
  {id:38,name:'Mushroom',category:'veggies',weight:4},
  {id:39,name:'Celery',category:'veggies',weight:4},
  {id:40,name:'Kale',category:'veggies',weight:4},
  {id:41,name:'Radish',category:'veggies',weight:4},
  {id:42,name:'Artichokes',category:'veggies',weight:4},
  {id:43,name:'Arugula',category:'veggies',weight:4},
  {id:44,name:'Spring Beans',category:'veggies',weight:4},
  {id:45,name:'Beets',category:'veggies',weight:4},
  {id:46,name:'Belgian Endive',category:'veggies',weight:4},
  {id:47,name:'Bok Choy',category:'veggies',weight:4},
  {id:48,name:'Broccoli Rabe',category:'veggies',weight:4},
  {id:49,name:'Brussel Sprouts',category:'veggies',weight:4},
  {id:50,name:'Cauliflower',category:'veggies',weight:4},
  {id:51,name:'Collard Greens',category:'veggies',weight:4},
  {id:52,name:'Crookneck',category:'veggies',weight:4},
  {id:53,name:'Fennel',category:'veggies',weight:4},
  {id:54,name:'Ginger Root',category:'veggies',weight:4},
  {id:55,name:'Horseradish',category:'veggies',weight:4},
  {id:56,name:'Jicama',category:'veggies',weight:4},
  {id:57,name:'Edamame',category:'veggies',weight:4},
  {id:58,name:'Lentils',category:'veggies',weight:4},
  {id:59,name:'Pinto beans',category:'veggies',weight:4},
  {id:60,name:'Black beans',category:'veggies',weight:4},
  {id:61,name:'Pickles',category:'veggies',weight:4},
  {id:62,name:'Olives',category:'veggies',weight:4}
  ];

  public fruits:Array<Ingredient>=[
    {id:63,name:'Tomato',category:'fruits',weight:7},
    {id:64,name:'Bell Pepper',category:'fruits',weight:7},
    {id:65,name:'Cucumber',category:'fruits',weight:7},
    {id:66,name:'Olives',category:'fruits',weight:7},
    {id:67,name:'Avocado',category:'fruits',weight:7},
    {id:68,name:'Banana',category:'fruits',weight:7},
    {id:69,name:'Pineapple',category:'fruits',weight:7},
    {id:70,name:'Cherry',category:'fruits',weight:7},
    {id:71,name:'Lemon',category:'fruits',weight:7},
    {id:72,name:'Lime',category:'fruits',weight:7},
    {id:73,name:'Orange',category:'fruits',weight:7},
    {id:74,name:'Pear',category:'fruits',weight:7},
    {id:75,name:'Mango',category:'fruits',weight:7},
    {id:76,name:'Jalepeno Pepper',category:'fruits',weight:7},
    {id:77,name:'Strawberry',category:'fruits',weight:7},
    {id:78,name:'Blueberry',category:'fruits',weight:7},
    {id:79,name:'Watermelon',category:'fruits',weight:7},
    {id:80,name:'Apple',category:'fruits',weight:7},
    {id:81,name:'Plum',category:'fruits',weight:7},
    {id:82,name:'Peach',category:'fruits',weight:7},
    {id:83,name:'Grapes',category:'fruits',weight:7},
    {id:84,name:'Coconut',category:'fruits',weight:7},
    {id:85,name:'Cherries',category:'fruits',weight:7},
    {id:86,name:'Raspberry',category:'fruits',weight:7},
    {id:87,name:'Blackberry',category:'fruits',weight:7}
    ];

  public dairy:Array<Ingredient>=[
    {id:88,name:'Buttermilk',category:'dairy',weight:5},
    {id:89,name:'Butter',category:'dairy',weight:5},
    {id:90,name:'Sour cream',category:'dairy',weight:5},
    {id:91,name:'Cheddar Cheese',category:'dairy',weight:5},
    {id:92,name:'Cottage Cheese',category:'dairy',weight:5},
    {id:93,name:'Mozzarella',category:'dairy',weight:5},
    {id:94,name:'Milk',category:'dairy',weight:5},
    {id:95,name:'Swiss Cheese',category:'dairy',weight:5},
    {id:96,name:'Cream',category:'dairy',weight:5},
    {id:97,name:'Cheese',category:'dairy',weight:5},
    {id:98,name:'Cream Cheese',category:'dairy',weight:5},
    {id:99,name:'Eggnog',category:'dairy',weight:5},
    {id:100,name:'Soymilk',category:'dairy',weight:5}
    ];
 
  public spices:Array<Ingredient>=[
    {id:101,name:'Lemon pepper',category:'spices',weight:2},
    {id:102,name:'Chili Powder',category:'spices',weight:2},
    {id:103,name:'Oregano',category:'spices',weight:2},
    {id:104,name:'Cayenne pepper',category:'spices',weight:2},
    {id:105,name:'Paprika',category:'spices',weight:2},
    {id:106,name:'Basil',category:'spices',weight:2},
    {id:107,name:'Red Pepper',category:'spices',weight:2},
    {id:108,name:'Pepper',category:'spices',weight:2},
    {id:109,name:'Salt',category:'spices',weight:2},
    {id:110,name:'Cumin',category:'spices',weight:2},
    {id:111,name:'Thyme',category:'spices',weight:2},
    {id:112,name:'Cinnamon',category:'spices',weight:2},
    {id:113,name:'Ginger',category:'spices',weight:2},
    {id:114,name:'Parsley',category:'spices',weight:2},
    {id:115,name:'Ketchup',category:'spices',weight:2},
    {id:116,name:'Mustard',category:'spices',weight:2},
    {id:117,name:'Sesame',category:'spices',weight:2},
    {id:118,name:'Onion powder',category:'spices',weight:2},
    {id:119,name:'Bay leaf',category:'spices',weight:2},
    {id:120,name:'Sugar',category:'spices',weight:2},
    {id:121,name:'Powdered sugar',category:'spices',weight:2},
    {id:121,name:'Cilantro',category:'spices',weight:2},
    {id:122,name:'Cloves',category:'spices',weight:2},
    {id:123,name:'Cream of tarter',category:'spices',weight:2},
    {id:124,name:'Curry powder',category:'spices',weight:2},
    {id:125,name:'Nutmeg',category:'spices',weight:2},
    {id:126,name:'Rosemary',category:'spices',weight:2},
    {id:127,name:'Vanilla extract',category:'spices',weight:2},
    {id:128,name:'Dill weed',category:'spices',weight:2},
    {id:129,name:'All spice',category:'spices',weight:2},
    {id:130,name:'Poppy seeds',category:'spices',weight:2},
    {id:131,name:'Peanut butter',category:'spices',weight:2},
    {id:132,name:'Jelly',category:'spices',weight:2},
    {id:133,name:'Soy sauce',category:'spices',weight:2}
    ];

    public starches:Array<Ingredient>=[
      {id:134,name:'White Rice',category:'grains',weight:15},
      {id:135,name:'Brown Rice',category:'grains',weight:15},
      {id:136,name:'Wheat',category:'grains',weight:15},
      {id:137,name:'Bread',category:'grains',weight:15},
      {id:138,name:'Rye',category:'grains',weight:15},
      {id:139,name:'Cornmeal',category:'grains',weight:15},
      {id:140,name:'Tortilla',category:'grains',weight:15},
      {id:141,name:'Rice',category:'grains',weight:15},
      {id:142,name:'Lasagna',category:'grains',weight:15},
      {id:143,name:'Linguini',category:'grains',weight:15},
      {id:144,name:'Spaghetti',category:'grains',weight:15},
      {id:145,name:'Fettucini',category:'grains',weight:15},
      {id:146,name:'Ravioli',category:'grains',weight:15},
      {id:147,name:'Baking powder',category:'grains',weight:15},
      {id:148,name:'Flour',category:'grains',weight:15},
      {id:149,name:'Oats',category:'grains',weight:15},
      {id:150,name:'Quinoa',category:'grains',weight:15}
      ];

      public pantry:Array<Ingredient>=[
        {id:1,name:'Beef',category:'meats', weight:12},
        {id:2,name:'Chicken',category:'meats', weight:12},
        {id:3,name:'Turkey',category:'meats', weight:12},
        {id:4,name:'Pork',category:'meats', weight:12},
        {id:5,name:'Shrimp',category:'meats', weight:12},
        {id:6,name:'Salmon',category:'meats', weight:12},
        {id:7,name:'Tuna',category:'meats', weight:12},
        {id:8,name:'Tilapia',category:'meats', weight:12},
        {id:9,name:'Halibut',category:'meats', weight:12},
        {id:10,name:'Lamb',category:'meats', weight:12},
        {id:11,name:'Sardines',category:'meats', weight:12},
        {id:12,name:'Liver',category:'meats', weight:12},
        {id:13,name:'Ham',category:'meats', weight:12},
        {id:14,name:'Bacon',category:'meats', weight:12},
        {id:15,name:'Tripe',category:'meats', weight:12},
        {id:16,name:'Scallop',category:'meats', weight:12},
        {id:17,name:'Anchovies',category:'meats', weight:12},
        {id:18,name:'Lobster',category:'meats', weight:12},
        {id:19,name:'Steak',category:'meats', weight:12},
        {id:20,name:'Egg',category:'meats', weight:12},
        {id:21,name:'Tofu',category:'meats', weight:12},
        {id:22,name:'Tempeh',category:'meats', weight:12},
        {id:23,name:'Broccoli',category:'veggies',weight:4},
        {id:24,name:'Squash',category:'veggies',weight:4},
        {id:25,name:'Spinach',category:'veggies',weight:4},
        {id:26,name:'Carrots',category:'veggies',weight:4},
        {id:27,name:'Onion',category:'veggies',weight:4},
        {id:28,name:'Cabbage',category:'veggies',weight:4},
        {id:29,name:'Zucchini',category:'veggies',weight:4},
        {id:30,name:'Eggplant',category:'veggies',weight:4},
        {id:31,name:'Corn',category:'veggies',weight:4},
        {id:32,name:'Lettuce',category:'veggies',weight:4},
        {id:33,name:'Chives',category:'veggies',weight:4},
        {id:34,name:'Asparagus',category:'veggies',weight:4},
        {id:35,name:'Garlic',category:'veggies',weight:4},
        {id:36,name:'Peas',category:'veggies',weight:4},
        {id:37,name:'Chickpea',category:'veggies',weight:4},
        {id:38,name:'Mushroom',category:'veggies',weight:4},
        {id:39,name:'Celery',category:'veggies',weight:4},
        {id:40,name:'Kale',category:'veggies',weight:4},
        {id:41,name:'Radish',category:'veggies',weight:4},
        {id:42,name:'Artichokes',category:'veggies',weight:4},
        {id:43,name:'Arugula',category:'veggies',weight:4},
        {id:44,name:'Spring Beans',category:'veggies',weight:4},
        {id:45,name:'Beets',category:'veggies',weight:4},
        {id:46,name:'Belgian Endive',category:'veggies',weight:4},
        {id:47,name:'Bok Choy',category:'veggies',weight:4},
        {id:48,name:'Broccoli Rabe',category:'veggies',weight:4},
        {id:49,name:'Brussel Sprouts',category:'veggies',weight:4},
        {id:50,name:'Cauliflower',category:'veggies',weight:4},
        {id:51,name:'Collard Greens',category:'veggies',weight:4},
        {id:52,name:'Crookneck',category:'veggies',weight:4},
        {id:53,name:'Fennel',category:'veggies',weight:4},
        {id:54,name:'Ginger Root',category:'veggies',weight:4},
        {id:55,name:'Horseradish',category:'veggies',weight:4},
        {id:56,name:'Jicama',category:'veggies',weight:4},
        {id:57,name:'Edamame',category:'veggies',weight:4},
        {id:58,name:'Lentils',category:'veggies',weight:4},
        {id:59,name:'Pinto beans',category:'veggies',weight:4},
        {id:60,name:'Black beans',category:'veggies',weight:4},
        {id:61,name:'Pickles',category:'veggies',weight:4},
        {id:62,name:'Olives',category:'veggies',weight:4},
          {id:63,name:'Tomato',category:'fruits',weight:7},
          {id:64,name:'Bell Pepper',category:'fruits',weight:7},
          {id:65,name:'Cucumber',category:'fruits',weight:7},
          {id:66,name:'Olives',category:'fruits',weight:7},
          {id:67,name:'Avocado',category:'fruits',weight:7},
          {id:68,name:'Banana',category:'fruits',weight:7},
          {id:69,name:'Pineapple',category:'fruits',weight:7},
          {id:70,name:'Cherry',category:'fruits',weight:7},
          {id:71,name:'Lemon',category:'fruits',weight:7},
          {id:72,name:'Lime',category:'fruits',weight:7},
          {id:73,name:'Orange',category:'fruits',weight:7},
          {id:74,name:'Pear',category:'fruits',weight:7},
          {id:75,name:'Mango',category:'fruits',weight:7},
          {id:76,name:'Jalepeno Pepper',category:'fruits',weight:7},
          {id:77,name:'Strawberry',category:'fruits',weight:7},
          {id:78,name:'Blueberry',category:'fruits',weight:7},
          {id:79,name:'Watermelon',category:'fruits',weight:7},
          {id:80,name:'Apple',category:'fruits',weight:7},
          {id:81,name:'Plum',category:'fruits',weight:7},
          {id:82,name:'Peach',category:'fruits',weight:7},
          {id:83,name:'Grapes',category:'fruits',weight:7},
          {id:84,name:'Coconut',category:'fruits',weight:7},
          {id:85,name:'Cherries',category:'fruits',weight:7},
          {id:86,name:'Raspberry',category:'fruits',weight:7},
          {id:87,name:'Blackberry',category:'fruits',weight:7},
          {id:88,name:'Buttermilk',category:'dairy',weight:5},
          {id:89,name:'Butter',category:'dairy',weight:5},
          {id:90,name:'Sour cream',category:'dairy',weight:5},
          {id:91,name:'Cheddar Cheese',category:'dairy',weight:5},
          {id:92,name:'Cottage Cheese',category:'dairy',weight:5},
          {id:93,name:'Mozzarella',category:'dairy',weight:5},
          {id:94,name:'Milk',category:'dairy',weight:5},
          {id:95,name:'Swiss Cheese',category:'dairy',weight:5},
          {id:96,name:'Cream',category:'dairy',weight:5},
          {id:97,name:'Cheese',category:'dairy',weight:5},
          {id:98,name:'Cream Cheese',category:'dairy',weight:5},
          {id:99,name:'Eggnog',category:'dairy',weight:5},
          {id:100,name:'Soymilk',category:'dairy',weight:5},
          {id:101,name:'Lemon pepper',category:'spices',weight:2},
          {id:102,name:'Chili Powder',category:'spices',weight:2},
          {id:103,name:'Oregano',category:'spices',weight:2},
          {id:104,name:'Cayenne pepper',category:'spices',weight:2},
          {id:105,name:'Paprika',category:'spices',weight:2},
          {id:106,name:'Basil',category:'spices',weight:2},
          {id:107,name:'Red Pepper',category:'spices',weight:2},
          {id:108,name:'Pepper',category:'spices',weight:2},
          {id:109,name:'Salt',category:'spices',weight:2},
          {id:110,name:'Cumin',category:'spices',weight:2},
          {id:111,name:'Thyme',category:'spices',weight:2},
          {id:112,name:'Cinnamon',category:'spices',weight:2},
          {id:113,name:'Ginger',category:'spices',weight:2},
          {id:114,name:'Parsley',category:'spices',weight:2},
          {id:115,name:'Ketchup',category:'spices',weight:2},
          {id:116,name:'Mustard',category:'spices',weight:2},
          {id:117,name:'Sesame',category:'spices',weight:2},
          {id:118,name:'Onion powder',category:'spices',weight:2},
          {id:119,name:'Bay leaf',category:'spices',weight:2},
          {id:120,name:'Sugar',category:'spices',weight:2},
          {id:121,name:'Powdered sugar',category:'spices',weight:2},
          {id:121,name:'Cilantro',category:'spices',weight:2},
          {id:122,name:'Cloves',category:'spices',weight:2},
          {id:123,name:'Cream of tarter',category:'spices',weight:2},
          {id:124,name:'Curry powder',category:'spices',weight:2},
          {id:125,name:'Nutmeg',category:'spices',weight:2},
          {id:126,name:'Rosemary',category:'spices',weight:2},
          {id:127,name:'Vanilla extract',category:'spices',weight:2},
          {id:128,name:'Dill weed',category:'spices',weight:2},
          {id:129,name:'All spice',category:'spices',weight:2},
          {id:130,name:'Poppy seeds',category:'spices',weight:2},
          {id:131,name:'Peanut butter',category:'spices',weight:2},
          {id:132,name:'Jelly',category:'spices',weight:2},
          {id:133,name:'Soy sauce',category:'spices',weight:2},
            {id:134,name:'White Rice',category:'grains',weight:15},
            {id:135,name:'Brown Rice',category:'grains',weight:15},
            {id:136,name:'Wheat',category:'grains',weight:15},
            {id:137,name:'Bread',category:'grains',weight:15},
            {id:138,name:'Rye',category:'grains',weight:15},
            {id:139,name:'Cornmeal',category:'grains',weight:15},
            {id:140,name:'Tortilla',category:'grains',weight:15},
            {id:141,name:'Rice',category:'grains',weight:15},
            {id:142,name:'Lasagna',category:'grains',weight:15},
            {id:143,name:'Linguini',category:'grains',weight:15},
            {id:144,name:'Spaghetti',category:'grains',weight:15},
            {id:145,name:'Fettucini',category:'grains',weight:15},
            {id:146,name:'Ravioli',category:'grains',weight:15},
            {id:147,name:'Baking powder',category:'grains',weight:15},
            {id:148,name:'Flour',category:'grains',weight:15},
            {id:149,name:'Oats',category:'grains',weight:15},
            {id:150,name:'Quinoa',category:'grains',weight:15}
      ];


      public getStarches() {
        return this.starches;
      }
      public getSpices() {
        return this.spices;
      }
      public getDairy() {
        return this.dairy;
      }
      public getFruits() {
        return this.fruits;
      }
      public getVeggies() {
        return this.veggies;
      }
      public getMeats() {
        return this.meats;
      }

      public getRecipes(){
        return this.therecipes;
      }

  constructor() { }
}
